### ISSUE TITLE
Adopt Sencha Cmd package structure

### ISSUE THREAD

**Issue by bentrm** [geoext/geoext2#299]
I think it would be nice to adopt the [package structure generated by Sencha Cmd](http://docs.sencha.com/cmd/5.x/cmd_packages/cmd_creating_packages.html). 

* ~~It would make it easier for new users to add GeoExt to an application by just cloning it into the `packages` directory and by adding it to the requires array in `app.json`. No further `Ext.Loader` configuration is required then.~~
* ~~Other packages could require GeoExt to extend it as well.~~
* Also, it would be easier to add required style definitions in the packages `sass` directory structure. (There is no harm to provide compiled css as well, of course.)
* ~~Finally, the `sencha app build` command would make it easy for users to produce a one-file build of the whole application including the required stylesheets.~~

While the link above describes most of the features, the only thing required for basic Cmd support is the following:
> While the above is quite extensive, the only parts that are required to be a package are these: "package.json" and ".sencha/package/sencha.cfg"

Maybe this is something that may be considered with #274 on it's way.

**Comment by bentrm** [comment]
Most of this is done already. Is there any interest to push GeoExt2 further by adapting SASS styling? Otherwise this can be closed.

**Comment by marcjansen** [comment]
Thanks for closing
