### ISSUE TITLE
Extjs5 support

### ISSUE THREAD

**Issue by geogeek11** [geoext/geoext2#340]
Hello, 
I would like to know if extjs5 branch is stable enough for production use, if not when extjs 5 would fully supported,  and when will the ol3 be supported ?

Thanks in advance

**Comment by marcjansen** [comment]
The extjs5 branch (#274) is basically ready for prime-time, but needs a little bit of history cleanup. I am doing this in #339.

I think it is reasonable to expect one or the other being merged within weeks from now.

The next big thing will be ol3, We have a little bit of time planned for this, but no real code is there yet (except for @bartvde's experiment in #291).
