### ISSUE TITLE
Printing WFS layer

### ISSUE THREAD

**Issue by fobetor** [geoext/geoext2#347]
Hi
 Perhaps someone can help , because I cant figure how to solve the following problem:
I am loading a wfs layer, so I can edit it. It's just a points layer, hosted in geoserver.
The points layer loads correctly on my map interface, the editing buttons, save buttons work correctly... but, when I want to print the map using Mapfish in geoserver, it fails. If I disable the points layer it works fine (it prints)
Looking the call for mapfish, I see that it seems that geoext is sending ALL the points and its charecteristics (DB fields) to geoserver to print. So, I conclude it is just overloading the mapfish service.
Is there a way of sending just the points, or telling to print from the geoserver directly, or symplifying the call without all the features info (I dont know why it is sent) or something?
 May be I am missing something about how to send a vector layer to geoserver mapfish using geoExt ...
Thanks
 Fernando

**Comment by chrismayer** [comment]
Hi, 
the first idea I had: Do you have your PrintProvider configured with method='POST'? In case you are using 'GET' maybe your URL is getting too long. See http://geoext.github.io/geoext2/docs/#!/api/GeoExt.data.MapfishPrintProvider-cfg-method

According to your idea to modify the feature before sending them to the print servlet: Here the ``beforeencodelayer`` event could be a possibility to achieve this. By this event you can modify the print layers before they are encoded for the request. See
http://geoext.github.io/geoext2/docs/#!/api/GeoExt.data.MapfishPrintProvider-event-beforeencodelayer

**Comment by fobetor** [comment]
Hi Christian
Thanks, yes, It was POST vs GET and the timeout setting.
Changing GET for POST works perfectly


Fernando
