### ISSUE TITLE
hierarchical layer trees

### ISSUE THREAD

**Issue by jgrocha** [geoext/geoext2#354]
Hi,

I used before two nice classes to create hierarchical layer trees, just by setting a property `group` (with the hierarchy divided by '/') in the layer definition. The classes are:
`GeoExt.tree.LayerTreeBuilder` (extends `GeoExt.tree.Panel`)
`GeoExt.tree.LayerGroupContainer` (extends `GeoExt.tree.LayerContainer`)

There is probably a reason for this classes have been taken away but I don't remember. Should I make a pull request to add them back to geoext2? Maybe with one example of usage?

Regards!

**Comment by marcjansen** [comment]
I have never used them, but am not opposed to have them in again. Was this GeoExt 1?

Anyhow, if you could give us some code, it'd be easier to see if we will merge this in. Thanks.

**Comment by jgrocha** [comment]
Hi Marc,

Thanks for the feedback. I've submmited a PR with these classes.

Regards!
