### ISSUE TITLE
Road to GeoExt 2.1.0 final

### ISSUE THREAD

**Issue by chrismayer** [geoext/geoext2#356]
This issue is a kind of roadmap towards the final release of GeoExt 2.1.0, which is currently in an alpha-state.

TODOs:

- [x] Finalize and merge relevant open pull requests:
  - [x] #352 
  - [x] #349
  - [x] #357
- [x] Adapt the README file according to the changed setup (#361)
- [x] Publish a first beta version 
- [x] Fix upcoming issues (optionally) 
- [x] Release final 2.1.0 version
- [x] Adapt the website (gh-pages)

**Comment by chrismayer** [comment]
I opened this to bring the release of GeoExt 2.1.0 up again. This is also meant as discussion platform. 

If I missed some TODOs please extend the list above.

**Comment by marcjansen** [comment]
> Adapt the README file according to the changed setup

What do you mean by that?

Does anyone have time to review the PRs? I can possibly do #352 if you thin it is ready (but @bentrm wanted to addsth.) but I won't have time for much more.

The website stuff is very important, I'll open a separate ticket.

**Comment by chrismayer** [comment]
>> Adapt the README file according to the changed setup

  > What do you mean by that?

I think there should be done some adaptions, mainly in the sections "What is GeoExt" and "Ok, I want to use GeoExt now..." because there are hints to ExtJS 4.2. This should be extended with the similar ExtJS 5 informations. I can do that.

I can take care of #355, maybe @weskamm can have a look at #349? Anyone there to take care of #357?

**Comment by marcjansen** [comment]
I just gave #357 a review. It is not ready to be merged yet.

**Comment by chrismayer** [comment]
I gave #355 a review. There are also still things to do before it can be merged. Since it is a more or less bigger thing a second review would be cool before final merge.

**Comment by chrismayer** [comment]
#355 is postponed to a follow up release since it is to much work to get it done until we want to release 2.1.0.
See discussion on the dev-list: http://www.geoext.org/pipermail/dev/2015-August/001295.html

**Comment by chrismayer** [comment]
Since #357 is the only open PR (and seems to be closed soon), I try to propose a timeline for the 2.1.0 release process:

  - Provide a beta version until 2015-09-04
  - Wait for feedback for one week
  - Optional roundtrip for bugfixes / adaptions according to feedback (1 week)
  - Release a final version and adapt depending resources (gh-pages, etc.) until the end of September

Any comments?

**Comment by marcjansen** [comment]
That sounds great! :+1:

**Comment by marcjansen** [comment]
Ping @chrismayer

**Comment by chrismayer** [comment]
Okay, I did the release for GeoExt 2.1.0, which is available here: https://github.com/geoext/geoext2/releases/tag/v2.1.0

I also updated the gh-pages branch with the current docs and examples as well as some adaptions to the index file of http://geoext.github.io/geoext2/. Feel free to have a look.

**Comment by chrismayer** [comment]
Just re-opened #359 since the online examples do not work properly when opened with HTTPS.

**Comment by marcjansen** [comment]
Aaaaargh! That was stupid, that we only did half the work in #359. Apologies!

Please ping us if you need help with fixing it. Very nice work with the release so far!

**Comment by chrismayer** [comment]
With c8e1d7fc which has been pushed to the gh-pages branch by me the online examples should be fine again. If you find any problems please report in #359.

**Comment by weskamm** [comment]
Thanks @chrismayer for all your efforts! :+1:

**Comment by chrismayer** [comment]
Since #359 is closed now, I suggest to close this as well and announce version 2.1.0 on the mailing lists.

**Comment by marcjansen** [comment]
Go for it! Thanks again!
