### ISSUE TITLE
How to use GeoExt2 with Sencha Architect3?

### ISSUE THREAD

**Issue by yejustme** [geoext/geoext2#385]
Hello:
     Could anyone tell me the way to use Geoext2 with Sencha Architect3(the visual tool to build UI rapidly)? Thanks very much.

**Comment by marcjansen** [comment]
I am not very experienced with the architect, but this page hints that you can include external ressourecs: https://docs.sencha.com/architect/3/creating_an_application/using_resources.html 

I don't know how well it integrates with the architect workflow, though.
