### ISSUE TITLE
Using GeoEXT2 store for Layer tree 

### ISSUE THREAD

**Issue by shahidnawazkhan** [geoext/geoext2#395]
I am sorry as this might not be the relevant platform for the question but i didn't get any help from anywhere that is why I am posting it here. 

I want to create a layer tree like the one given in the below example. 
https://iris.gov.gr/SoilServices/danger.html

The example finely works when i implement the same on my own system it doesn't work and I don't know much about the complexities of GeoEXT. 

I am writing my code here below and the error that I get. 
**Here is the code for the Store:**
var store = Ext.create('Ext.data.TreeStore', {
            model: 'GeoExt.data.LayerTreeModel',
            root: {
            	 text: "Root",
                expanded: true,
                children: [
				  {
                	text: "Θεματικοί Χάρτες",
                    leaf: false,
                    expanded: true,
                    children: [
                        {
                            text: sppsq.name,
                            layer: sppsq,
                            leaf: true,
                            checked: false,
                            children: [],
                            nodeType: "gx_overlaylayercontainer"
                        },
                        {
                            text: elecag.name,
                            layer: elecag,
                            leaf: true,
                            checked: false,
                            children: [],
                            nodeType: "gx_overlaylayercontainer"
                        },
                    ]
                },       
                {
                 plugins: [{
                      ptype: 'gx_baselayercontainer',
                      loader: {store: mapPanel.layers} // BASE "REFERENCE" LAYERS FROM arcticMapPanel
                  }],
                  expanded: true,
                  text: 'Υπόβαθρα'
              }
            ]
            }
        });

**Below is the code for tree:**
_var tree = Ext.create('GeoExt.tree.Panel', {
            border: true,
            region: "west",
            title: "Επίπεδα",
            width: 290,
            split: true,
            collapsible: true,
            collapseMode: "mini",
            autoScroll: true,
            store: store,
            rootVisible: false,
            lines: false,
            listeners: {
        checkchange: {
        	fn: function (record, checked, opts) {
        		record.data.layer.setVisibility(checked)
       			 }
            }
            }
        }
        );

**Error Got:**
too much recursion
http://cdn.sencha.com/ext/gpl/5.1.0/build/ext-all-debug.js
Line 1759

**Comment by chrismayer** [comment]
Hi @shahidnawazkhan ,

you are right, this is not the right platform to ask such questions. The "issues"-section here in github is only for reporting software bugs in GeoExt itself. At the first sight this does not seem the case here.
Can you please post your question to the mailing list: http://www.geoext.org/cgi-bin/mailman/listinfo/users? I am sure you will get help there.
If it comes out that this is a bug in GeoExt itself we will re-open this issue.
Thank you!

**Comment by shahidnawazkhan** [comment]
Can anyone else reply as I didn't got any reply in the Geoext mailing lists

**Comment by chrismayer** [comment]
> Can anyone else reply as I didn't got any reply in the Geoext mailing lists

That is not true, I personally answered your question on the mailing list. See http://www.geoext.org/pipermail/users/2017-March/003543.html
